
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.*;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp-
 */
 
public class Front extends javax.swing.JFrame {
  

   // private javax.swing.JPanel studentPanel;
    //private javax.swing.JPanel teacherJPanel;
    /**
     * Creates new form Front
     */
    private Socket socket;
    ObjectOutputStream doout;
    ObjectInputStream doin;
    DataOutputStream dout;
    DataInputStream din;
   // DataOutputStream d;
    BufferedReader in;
    AdminData msgAdmin;
    String str;
    StudentData msgStudent;
    TeacherData msgTeacher;
    private int PORT;
    private String HOST;
        public void MultiInputPane()
        {
            JTextField hostField = new JTextField(5);
          JTextField portField = new JTextField(5);

          JPanel myPanel = new JPanel();
          myPanel.add(new JLabel("HOST:"));
          myPanel.add(hostField);
          myPanel.add(Box.createHorizontalStrut(15)); // a spacer
          myPanel.add(new JLabel("PORT:"));
          myPanel.add(portField);

          int result = JOptionPane.showConfirmDialog(null, myPanel, 
                   "Please Enter The Valid Values", JOptionPane.OK_CANCEL_OPTION);
          if (result == JOptionPane.OK_OPTION) {
             System.out.println("x value: " + hostField.getText());
             System.out.println("y value: " + portField.getText());
        }
          HOST=hostField.getText();
          PORT=Integer.parseInt(portField.getText());
        }

    public Front() {
        HOST="127.0.0.1";
        PORT=5000;
        try{
        MultiInputPane();
        }
        catch(Exception e){
            ;
        }
        msgStudent=new StudentData();
        msgTeacher=new TeacherData();
        msgAdmin=new AdminData();
        try{
        socket =new Socket(HOST,PORT);
        doout=new ObjectOutputStream(socket.getOutputStream());  
        doin=new ObjectInputStream(socket.getInputStream());
        dout=new DataOutputStream(socket.getOutputStream());
        din=new DataInputStream(socket.getInputStream());
       // d=new DataOutputStream(socket.getOutputStream());
        //in=new BufferedReader(new InputStreamReader(System.in));
        str="";
            System.out.println((socket.getInetAddress().toString()).substring(1));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Unable to set up connection");
            System.out.println("Unable to set up connection");
        }
        initComponents();
        jPanel2.setBackground(Color.blue);
        studentPanel.setBackground(Color.blue);
         this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.addWindowListener(new 
        WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent event) {
            try {
                socket.close();
            } catch (IOException ex) {
                Logger.getLogger(TeacherUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                    
        }

            private void setDefaultCloseOperation(int EXIT_ON_CLOSE) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        teacherPanel = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        studentPanel = new javax.swing.JPanel();
        studentLabel = new javax.swing.JLabel();
        studentPasswordLabel = new javax.swing.JLabel();
        studentUsernameTextField = new javax.swing.JTextField();
        studentPasswordField = new javax.swing.JPasswordField();
        studentLoginButton = new javax.swing.JButton();
        studentPanel2 = new javax.swing.JPanel();
        studentAccountLabel = new javax.swing.JLabel();
        studentNameLabel = new javax.swing.JLabel();
        studentEmailLabel = new javax.swing.JLabel();
        studentUsernameLabel = new javax.swing.JLabel();
        studentPasswordSignupLabel = new javax.swing.JLabel();
        studentNameTextField = new javax.swing.JTextField();
        studentEmailTextField = new javax.swing.JTextField();
        studentUsernameSignupTextField = new javax.swing.JTextField();
        studentSignupButton = new javax.swing.JButton();
        studentSignupPasswordField = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        teacherPanel1 = new javax.swing.JPanel();
        studentPanel1 = new javax.swing.JPanel();
        teacherRefenceLabel = new javax.swing.JLabel();
        teacherPasswordLabel = new javax.swing.JLabel();
        teacherReferenceTextField = new javax.swing.JTextField();
        teacherPasswordField = new javax.swing.JPasswordField();
        teacherLoginButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        teacherPanel2 = new javax.swing.JPanel();
        teacherAccountLabel = new javax.swing.JLabel();
        teacherNameLabel = new javax.swing.JLabel();
        teacherEmailLabel = new javax.swing.JLabel();
        teacherReferenceLabel = new javax.swing.JLabel();
        teacherPasswordSignupLabel = new javax.swing.JLabel();
        teacherNameTextField = new javax.swing.JTextField();
        teacherEmailTextField = new javax.swing.JTextField();
        teacherReferenceSignupTextField = new javax.swing.JTextField();
        teacherSignupButton = new javax.swing.JButton();
        teacherSignupPasswordField = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        adminPasswordLabel = new javax.swing.JLabel();
        adminUsernameLabel = new javax.swing.JLabel();
        adminUsernameTextField = new javax.swing.JTextField();
        adminPasswordField = new javax.swing.JPasswordField();
        adminLogIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(255, 255, 153));
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tutor's Point");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        studentLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        studentLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentLabel.setText("Username");

        studentPasswordLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        studentPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentPasswordLabel.setText("Password");

        studentUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentUsernameTextFieldActionPerformed(evt);
            }
        });

        studentPasswordField.setText("jPasswordField1");

        studentLoginButton.setBackground(new java.awt.Color(10, 0, 255));
        studentLoginButton.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        studentLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        studentLoginButton.setText("Login");
        studentLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addComponent(studentPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addComponent(studentPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(studentLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentLoginButton))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        studentPanel2.setBackground(new java.awt.Color(0, 0, 255));

        studentAccountLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 25)); // NOI18N
        studentAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentAccountLabel.setText("Create a new account");

        studentNameLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        studentNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentNameLabel.setText("Name");

        studentEmailLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        studentEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentEmailLabel.setText("E-mail");

        studentUsernameLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        studentUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentUsernameLabel.setText("Username");

        studentPasswordSignupLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        studentPasswordSignupLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentPasswordSignupLabel.setText("Password");

        studentNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameTextFieldActionPerformed(evt);
            }
        });

        studentEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentEmailTextFieldActionPerformed(evt);
            }
        });

        studentUsernameSignupTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentUsernameSignupTextFieldActionPerformed(evt);
            }
        });

        studentSignupButton.setBackground(new java.awt.Color(0, 153, 0));
        studentSignupButton.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        studentSignupButton.setForeground(new java.awt.Color(255, 255, 255));
        studentSignupButton.setText("Sign Up");
        studentSignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSignupButtonActionPerformed(evt);
            }
        });

        studentSignupPasswordField.setText("jPasswordField1");

        javax.swing.GroupLayout studentPanel2Layout = new javax.swing.GroupLayout(studentPanel2);
        studentPanel2.setLayout(studentPanel2Layout);
        studentPanel2Layout.setHorizontalGroup(
            studentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanel2Layout.createSequentialGroup()
                .addGroup(studentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(studentAccountLabel))
                    .addGroup(studentPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(studentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentPasswordSignupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addGroup(studentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentUsernameSignupTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(studentEmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(studentNameTextField)
                            .addComponent(studentSignupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentSignupPasswordField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentPanel2Layout.setVerticalGroup(
            studentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentAccountLabel)
                .addGap(18, 18, 18)
                .addGroup(studentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentUsernameSignupTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentPasswordSignupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentSignupPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(studentSignupButton)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(studentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(studentPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        teacherPanel.addTab("Student", jPanel3);

        teacherPanel1.setBackground(new java.awt.Color(0, 0, 255));

        studentPanel1.setBackground(new java.awt.Color(0, 0, 255));

        teacherRefenceLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        teacherRefenceLabel.setForeground(new java.awt.Color(255, 255, 255));
        teacherRefenceLabel.setText("Reference Number");

        teacherPasswordLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        teacherPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        teacherPasswordLabel.setText("Password");

        teacherReferenceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherReferenceTextFieldActionPerformed(evt);
            }
        });

        teacherPasswordField.setText("jPasswordField1");

        teacherLoginButton.setBackground(new java.awt.Color(10, 0, 255));
        teacherLoginButton.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        teacherLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        teacherLoginButton.setText("Login");
        teacherLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentPanel1Layout = new javax.swing.GroupLayout(studentPanel1);
        studentPanel1.setLayout(studentPanel1Layout);
        studentPanel1Layout.setHorizontalGroup(
            studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(teacherReferenceTextField)
                    .addComponent(teacherRefenceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addGap(95, 95, 95)
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentPanel1Layout.createSequentialGroup()
                        .addComponent(teacherPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(studentPanel1Layout.createSequentialGroup()
                        .addComponent(teacherPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(teacherLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        studentPanel1Layout.setVerticalGroup(
            studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherRefenceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherReferenceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherLoginButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout teacherPanel1Layout = new javax.swing.GroupLayout(teacherPanel1);
        teacherPanel1.setLayout(teacherPanel1Layout);
        teacherPanel1Layout.setHorizontalGroup(
            teacherPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        teacherPanel1Layout.setVerticalGroup(
            teacherPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherPanel1Layout.createSequentialGroup()
                .addComponent(studentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        teacherPanel2.setBackground(new java.awt.Color(0, 0, 255));

        teacherAccountLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 25)); // NOI18N
        teacherAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        teacherAccountLabel.setText("Create a new account");

        teacherNameLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        teacherNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        teacherNameLabel.setText("Name");

        teacherEmailLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        teacherEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        teacherEmailLabel.setText("E-mail");

        teacherReferenceLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        teacherReferenceLabel.setForeground(new java.awt.Color(255, 255, 255));
        teacherReferenceLabel.setText("Reference Number ");

        teacherPasswordSignupLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        teacherPasswordSignupLabel.setForeground(new java.awt.Color(255, 255, 255));
        teacherPasswordSignupLabel.setText("Password");

        teacherNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherNameTextFieldActionPerformed(evt);
            }
        });

        teacherEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherEmailTextFieldActionPerformed(evt);
            }
        });

        teacherReferenceSignupTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherReferenceSignupTextFieldActionPerformed(evt);
            }
        });

        teacherSignupButton.setBackground(new java.awt.Color(0, 153, 0));
        teacherSignupButton.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        teacherSignupButton.setForeground(new java.awt.Color(255, 255, 255));
        teacherSignupButton.setText("Sign Up");
        teacherSignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherSignupButtonActionPerformed(evt);
            }
        });

        teacherSignupPasswordField.setText("jPasswordField1");

        javax.swing.GroupLayout teacherPanel2Layout = new javax.swing.GroupLayout(teacherPanel2);
        teacherPanel2.setLayout(teacherPanel2Layout);
        teacherPanel2Layout.setHorizontalGroup(
            teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherPanel2Layout.createSequentialGroup()
                .addGroup(teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(teacherAccountLabel))
                    .addGroup(teacherPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teacherNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teacherEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teacherPasswordSignupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teacherReferenceLabel))
                        .addGap(45, 45, 45)
                        .addGroup(teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teacherReferenceSignupTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(teacherEmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(teacherNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(teacherSignupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teacherSignupPasswordField))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        teacherPanel2Layout.setVerticalGroup(
            teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherAccountLabel)
                .addGap(18, 18, 18)
                .addGroup(teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherReferenceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherReferenceSignupTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherPasswordSignupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherSignupPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(teacherSignupButton)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(teacherPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(teacherPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(4, 4, 4)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teacherPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(teacherPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        teacherPanel.addTab("Teacher", jPanel4);

        jPanel7.setBackground(new java.awt.Color(51, 102, 255));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setToolTipText("");

        adminPasswordLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        adminPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminPasswordLabel.setText("Password");

        adminUsernameLabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        adminUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminUsernameLabel.setText("Username");

        adminUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUsernameTextFieldActionPerformed(evt);
            }
        });

        adminPasswordField.setText("jPasswordField1");
        adminPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPasswordFieldActionPerformed(evt);
            }
        });

        adminLogIn.setFont(new java.awt.Font("Monotype Corsiva", 3, 20)); // NOI18N
        adminLogIn.setText("Log In");
        adminLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adminUsernameTextField)
                            .addComponent(adminPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(adminLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(adminLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        teacherPanel.addTab("Administrator", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherPanel))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherPanel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teacherSignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherSignupButtonActionPerformed
        // TODO add your handling code here:
        msgTeacher.setEmail(teacherEmailTextField.getText());
        msgTeacher.setName(teacherNameTextField.getText());
        msgTeacher.setPassword(teacherSignupPasswordField.getText());
        msgTeacher.setReference(teacherReferenceSignupTextField.getText());
        msgTeacher.setRequest(4);
        /*int ref=Integer.parseInt(msgTeacher.getReferece().toString());

        String name =msgTeacher.getName();
        String password=msgTeacher.getPassword();
        String email=msgTeacher.getEmail();
        String query="Update teachers set name='"+name+"',password='"+password+"',email='"+email+"',signup=1 where ref="+ref+"and signup=0";
        */
        try{

            doout.writeObject(msgTeacher);
            str=(String)din.readUTF();
            int response=Integer.parseInt(str);

            // int response=Integer.parseInt(str);
            if(response==1){
                JOptionPane.showMessageDialog(this,"Account Created");
            }
            else {
                JOptionPane.showMessageDialog(this, "Access Denied");
            }
            doout.reset();

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_teacherSignupButtonActionPerformed

    private void teacherReferenceSignupTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherReferenceSignupTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherReferenceSignupTextFieldActionPerformed

    private void teacherEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherEmailTextFieldActionPerformed

    private void teacherNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherNameTextFieldActionPerformed

    private void teacherLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherLoginButtonActionPerformed
        // TODO add your handling code here:
        msgTeacher.setEmail(teacherEmailTextField.getText());
        msgTeacher.setName(teacherNameTextField.getText());
        msgTeacher.setPassword(teacherPasswordField.getText());
        msgTeacher.setReference(teacherReferenceTextField.getText());
        msgTeacher.setRequest(3);
        try{
            doout.writeObject(msgTeacher);
            str=(String)din.readUTF();
            int response=Integer.parseInt(str);
            if(response==1){
                JOptionPane.showMessageDialog(this,"Access Enabled");
                msgTeacher.setName((String)din.readUTF());
                System.out.println("1");
                this.dispose();
                System.out.println("2");
                String ar[]=new String[2];
                new TeacherUI(doout,doin,dout,din,socket,msgTeacher).setVisible(true);

            }
            else {
                JOptionPane.showMessageDialog(this, "Access Denied");
            }
            doout.reset();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_teacherLoginButtonActionPerformed

    private void teacherReferenceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherReferenceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherReferenceTextFieldActionPerformed

    private void studentSignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSignupButtonActionPerformed
        // TODO add your handling code here:
        msgStudent.setEmail(studentEmailTextField.getText());
        msgStudent.setName(studentNameTextField.getText());
        msgStudent.setPassword(studentSignupPasswordField.getText());
        msgStudent.setUsername(studentUsernameSignupTextField.getText());
        msgStudent.setRequest(1);
        try{
            doout.writeObject(msgStudent);
            str=(String)din.readUTF();
            int response=Integer.parseInt(str);
            if(response==1){
                JOptionPane.showMessageDialog(this,"Account Created");
            }
            else {
                JOptionPane.showMessageDialog(this, "Choose another username");
            }
            doout.reset();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_studentSignupButtonActionPerformed

    private void studentUsernameSignupTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentUsernameSignupTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentUsernameSignupTextFieldActionPerformed

    private void studentEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentEmailTextFieldActionPerformed

    private void studentNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameTextFieldActionPerformed

    private void studentLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentLoginButtonActionPerformed
        // TODO add your handling code here:
        msgStudent.setEmail(studentEmailTextField.getText().toString());
        msgStudent.setName(studentUsernameTextField.getText());
        msgStudent.setPassword(studentPasswordField.getText());
        msgStudent.setUsername(studentUsernameTextField.getText().toString());

        //msgStudent.setPassword(studentPasswordField.getText());
        // msgStudent.setUsername(studentUsernameSignupTextField.getText());
        msgStudent.setRequest(0);
        try{
            //d.writeUTF("Hi");
            doout.writeObject(msgStudent);
            str=(String)din.readUTF();
            System.out.println(str);
            int response=Integer.parseInt(str);
            if(response==1){
                msgStudent.setName((String)din.readUTF());
                JOptionPane.showMessageDialog(this,"Access Enabled");
                System.out.println("1");
                this.dispose();
                System.out.println("2");
                String ar[]=new String[2];
                new StudentUI(doout,doin,dout,din,socket,msgStudent).setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(this, "Access Denied");
            }
            doout.reset();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_studentLoginButtonActionPerformed

    private void studentUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentUsernameTextFieldActionPerformed

    private void adminUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminUsernameTextFieldActionPerformed

    private void adminPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPasswordFieldActionPerformed

    private void adminLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogInActionPerformed
        // TODO add your handling code here:
        msgAdmin.setUsername(adminUsernameTextField.getText().toString());
        msgAdmin.setPassword(adminPasswordField.getText().toString());
        
        msgAdmin.setRequest(14);
        try{
            //d.writeUTF("Hi");
            doout.writeObject(msgAdmin);
            str=(String)din.readUTF();
            System.out.println(str);
            int response=Integer.parseInt(str);
            if(response==1){
                JOptionPane.showMessageDialog(this,"Access Enabled");
                System.out.println("1");
                this.dispose();
                System.out.println("2");
                String ar[]=new String[2];
                new AdminUI(doout,doin,dout,din,socket).setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(this, "Access Denied");
            }
            doout.reset();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_adminLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
            for(LookAndFeelInfo info: UIManager.getInstalledLookAndFeels()){
                if("Nimbus".equals(info.getName())){
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminLogIn;
    private javax.swing.JPasswordField adminPasswordField;
    private javax.swing.JLabel adminPasswordLabel;
    private javax.swing.JLabel adminUsernameLabel;
    private javax.swing.JTextField adminUsernameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel studentAccountLabel;
    private javax.swing.JLabel studentEmailLabel;
    private javax.swing.JTextField studentEmailTextField;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JButton studentLoginButton;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JTextField studentNameTextField;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JPanel studentPanel1;
    private javax.swing.JPanel studentPanel2;
    private javax.swing.JPasswordField studentPasswordField;
    private javax.swing.JLabel studentPasswordLabel;
    private javax.swing.JLabel studentPasswordSignupLabel;
    private javax.swing.JButton studentSignupButton;
    private javax.swing.JPasswordField studentSignupPasswordField;
    private javax.swing.JLabel studentUsernameLabel;
    private javax.swing.JTextField studentUsernameSignupTextField;
    private javax.swing.JTextField studentUsernameTextField;
    private javax.swing.JLabel teacherAccountLabel;
    private javax.swing.JLabel teacherEmailLabel;
    private javax.swing.JTextField teacherEmailTextField;
    private javax.swing.JButton teacherLoginButton;
    private javax.swing.JLabel teacherNameLabel;
    private javax.swing.JTextField teacherNameTextField;
    private javax.swing.JTabbedPane teacherPanel;
    private javax.swing.JPanel teacherPanel1;
    private javax.swing.JPanel teacherPanel2;
    private javax.swing.JPasswordField teacherPasswordField;
    private javax.swing.JLabel teacherPasswordLabel;
    private javax.swing.JLabel teacherPasswordSignupLabel;
    private javax.swing.JLabel teacherRefenceLabel;
    private javax.swing.JLabel teacherReferenceLabel;
    private javax.swing.JTextField teacherReferenceSignupTextField;
    private javax.swing.JTextField teacherReferenceTextField;
    private javax.swing.JButton teacherSignupButton;
    private javax.swing.JPasswordField teacherSignupPasswordField;
    // End of variables declaration//GEN-END:variables
}
